### PR TITLE
feat: use config from application

### PR DESCRIPTION
**Pull request by patzick**
This allows the plugin to be dynamic (no hardcoded addresses and access token), but we can do even better - we'll provide GET and POST (for start) methods to API Client. So used could do:
```js
import {apiGet} from '@shopware-pwa/shopware-6-client'

// and in mounted
await apiGet('/my-plugin-extension-endpoint')
```

this is also needed, because of contextToken, which may wary during user session and also should be attached.

## Config changes
what would be great to implement this plugin if `pwa-bundles.json` could present something like:
```json
{
  "swag-vue-storefront": {
    "configuration": {}
  },
  "swag-hello-cody": {
    "configuration": {
      "slots": [
        {
          "name": "SwPluginTopNavigation",
          "file": "main.vue"
        }
      ]
    }
  }
}
```

@elkmod is that possible, or we would need to create such configuration inside the resources directory?

### CODE REVIEW

**Comment by elkmod** [comment]
Really like the proposed API for making requests against the Shopware API. This would also set the developers free from explicitly having to set the token and URL right?

**Concerning the configuration**

Technically, we could do that. However, I am a bit sensible about mixing plugin-metadata (like installation date, configuration as set per user) and extension-related configuration (like the slot extensions/configuration like proposed above). The cleanest way to keep those two separated would be to create some kind of `slot-configuration.json` within the `Resources/pwa` directory which does exactly that mapping. If you wish, we can read this file programatically and merge it into the `pwa-bundles.json` output. However, since the `pwa-bundles-assets` contains every file from `Resources/pwa` we would duplicate that configuration.

So I'd suggest to create the `slot-configuration.json` file which defines the mappings slot => component file inside the `Resources/pwa` directory. This will be exported together with the other "assets" and then be available for you.

**Comment by patzick** [comment]
yeah, then the user just invoke his endpoint as in the example, and it will be invoked with the current context, so as logged in user, or with some specific language etc :)

I thought so, that's why I asked about that. For me, and I agree, even for developers will be easier to create such file to fill into specific slots. It also gives a lot of flexibility.
So the only question for now left is use case like this (it's not for HelloCody example, and pretty abstract, as assets can be inside plugins as well):
Created a plugin, which shows an image from a specific UR set after plugin installation. So after plugin installation, I can set this url via configuration inside Shopware Administration site and save it.
Q: how it will be presented in configuration file?

**Comment by elkmod** [comment]
Exactly - these kinds of parameters will be set programatically (because they are not necessarily specific to the PWA) and then additional output to the pwa-bundles.json config:

```
{
    "swag-pay-pal": {
        "configuration": {
            "settings": {
                "ecsListingEnabled": true,
                "intent": "sale",
                "ecsDetailEnabled": true,
                "spbAlternativePaymentMethodsEnabled": true,
                "plusCheckoutEnabled": true,
                "spbCheckoutEnabled": true,
                "ecsCartEnabled": true,
                "merchantLocation": "germany",
                "spbButtonShape": "rect",
                "spbButtonColor": "gold",
                "submitCart": true,
                "ecsOffCanvasEnabled": true,
                "sendOrderNumber": true,
                "installmentBannerEnabled": true,
                "ecsButtonColor": "gold",
                "landingPage": "Login",
                "ecsSubmitCart": true,
                "ecsLoginEnabled": true,
                "ecsButtonShape": "rect",
                "sandbox": false
            }
        },
        "installedAt": "2020-02-24 10:23:17",
        "version": "1.1.0"
    },
    "swag-vue-storefront": {
        "configuration": [],
        "installedAt": "2020-02-24 10:23:31",
        "version": "0.0.1"
    },
    "swag-hello-cody": {
        "configuration": [],
        "installedAt": "2020-02-24 10:34:36",
        "version": "9999999-dev"
    }
}
```

**Comment by patzick** [comment]
Great, so what do you think about this proposal:
Everyone in their plugins resources folder will have a file `config.json` with slots configuration and default values for config properties. Then CLI will parse `pwa-bundles.json` and merge settings into that file. So component will have just something like this:
```js
import config from './config.json'
```
and for development, it uses default values, and after installation - values from admin panel

**Comment by elkmod** [comment]
Sounds good. You could even use values from admin panel during development, if you explicitly dump the bundles before and paste them manually. What I mean is, that there should be at least a way to alter the config values during development.

**Comment by patzick** [comment]
Sure, I agree and this will come in next step :) So merging for now and will prepare these API client methods shortly!

**Pull request merged**
